### ISSUE TITLE
Add example notebook for ensemble optimization

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#11]
Add an example notebook that performs an ensemble optimization of a Rydberg gate, as in Phys. Rev. A 90, 032329 (2014)

This will be easier with #10

**Comment by goerz** [comment]
Prerequisite for #13

**Comment by goerz** [comment]
With #10 being closed, I think everything is now in place for this example.

**Comment by goerz** [comment]
@MatthiKrauss How are you doing on this?

**Comment by MatthiKrauss** [comment]
I already had the model defined, but I was some trouble using the collapse operators which can be assigned in the gate_objectives routine. The optimization gives me a 'NotImplementedError: Liouville exponentiation not implemented'. So am I doing something wrong there or is it not yet implemented and should circumvent this?

**Comment by goerz** [comment]
Can you make a branch and push the notebook in its current state? See https://krotov.readthedocs.io/en/latest/02_contributing.html#how-to-commit-failing-tests-or-example-notebooks and https://krotov.readthedocs.io/en/latest/02_contributing.html#how-to-work-on-a-topic-branch. I'll have a look.

**Comment by goerz** [comment]
Indeed, `expm` is not implemented for `c_ops`. Generally, it is much better to use `qutip.liouvillian` to convert the combination of `H` and `c_ops` into a Liouvillian and store that in `Objective.H`. Keeping the `c_ops` explicitly would only be useful for a MCWF propagation, I think. The only reason I haven't removed `c_ops` from `Objective` is that I don't want to cut off that possibility, as an "advanced" use case.

I also wasn't anticipating that this example would have Lindblad operators... But as I said, I'll have a look.

**Comment by MatthiKrauss** [comment]
Sorry for the late reply, I pushed now a first version. However, I added a "liouvillianize" function which converts the Hamiltonian to a Liouvillian, such as in notebook 04 from Daniel.
I also had some trouble with the optimize_pulses routine, since the kernel was shutting down when calling it. However, Daniel B. told me how to fix it (reinstall QuTIP from source).

**Comment by goerz** [comment]
> I also wasn't anticipating that this example would have Lindblad operators
I totally forgot we actually used density matrices in that paper, so you're fine.

**Comment by Basilewitsch** [comment]
> @Basilewitsch Can you open an issue on qutip about these crashes? Maybe more reports will motivate them to look their long-standing Cython problems

I haven't done this so far, since I'm not sure which steps produce/reproduce the problem and I don't want to raise an issue with insufficient information

**Comment by goerz** [comment]
I should be available for Skype on most days. You can also reach me anytime on [Gitter](https://gitter.im/qucontrol_krotov/Lobby), especially through the "Chat Privately" button that you'll see when hovering over my avatar.

Merry Christmas to you and everyone!

**Comment by goerz** [comment]
> According to the problems with the gate_objectives, I thought, that the function `krotov.gate_objective` is exactly doing this (taking the threes states from the NJP paper)

You're right that the `gate_objectives` routine should automatically handle this when it detects that the system is dissipative. This is planned for the very near future.

**Comment by goerz** [comment]
After this is merged into master, please

* [ ] add a link to the example notebook in "How to optimize for robust pulss" (`docs/11_howto.rst`)

**Comment by goerz** [comment]
@MatthiKrauss Can you push your most current version of this notebook as soon as possible?
