### ISSUE TITLE
Update example notebook for simple gate optimization

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#27]
The "X-Gate for a Transmon Qubit" example is a very simple example of a gate optimization, and thus it fits in quite well into into the progression of example notebooks, as the first example for a gate optimization. It is preceded by state-to-state optimizations and followed up by more complex gate optimization (dissipative "3 states" optimization, and perfect entanglers).

However, the example could need a little bit of cleanup, and an extended discussion.

Prerequisite for #13

**Comment by goerz** [comment]
@FernandoGago Would you have time to expand this example a little bit?

**Comment by FernandoGago** [comment]
Yes, I will take care of this as soon as possible.

**Comment by goerz** [comment]
That looks pretty good already! A few comments:

* Since this is a fast-oscillating pulse: I think we have to evaluate whether dt is sufficiently small by checking that we get the same state if we propagate the guess pulse with twice the number of `tlist` points. The alternative would be to apply a RWA.
* What is the physical mechanism that generates the potential? Current? Magnetic Flux through a split junction?
* Comment on the choice of guess pulse
* Plot and discuss the spectrum of guess/optimized pulse
* Why doesn't the guess pulse do anything? At a glance, it seems like it's a resonant pulse for the 0 → 1 transition, so I would have expected some Rabi cycling?
* I'm not sure that plotting phase over time is very interesting. It should be enough to print how much the phase of the propagated state deviates from the phase 0 of the target state.

**Comment by FernandoGago** [comment]
Sorry for taking so long, but I am finally back from my holidays. 

I will try to implement all the suggestions that you made. 

Regarding the physical meaning of the interaction, it is actually a potential V(t) that is being applied to the transmon. So the actual term in the Hamiltonian is - \Op{q} V(t), where \Op{q} is the charge operator which is diagonal in the charge basis. However I am not sure how it is written in the eigenstate basis. Usually for a Rabi cycling we need a interaction Hamiltonian which is nonzero in the diagonals +1 and -1. For this system, after changing the basis, I believe that was (almost) the case when I checked many, many months ago, so I still don't know why is this behaving so badly. 

I am going to make a couple of changes and tests to see what I can do with this point from the list.
