### ISSUE TITLE
parallel_map does not give expected performance

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#29]
Calling `optimize_pulses` with `parallel_map=qutip.parallel.parallel_map`, e.g. in the example for the gate optimization (#27) does not result in the expected speedup by a factor of two. Instead, it appears to run much much slower than the non-parallelized version. This could be a bug in qutip, but we'll have to investigate. In any case, we need to make sure there is a way to run the optimization with parallelization, and  the gate optimization seems like a good example where to show this (as well as the ensemble optimization example, #11)

**Comment by christianekoch** [comment]
I am impressed how quickly you found and implemented this work-around, chapeau!
