### ISSUE TITLE
Add example notebook for state-to-state transfer in Lambda system, in the RWA

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#3]
Add an example notebook that optimizes the transfer from state 1 to state 3 in a Lambda-sytem, with a Pump and a Stokes laser, without dissipation, and in the rotating wave approximation.

At a technical level, this is mainly to illustrate (and test) the use of complex control fields.

**Comment by goerz** [comment]
Prerequisite for #13

**Comment by goerz** [comment]
@karl-horn So this example will now mainly illustrate how to rewrite complex control fields into two real control fields, see [How to optimize complex control fields](https://krotov.readthedocs.io/en/latest/howto.html#how-to-optimize-complex-control-fields)  in the documentation.

**Comment by goerz** [comment]
@karl-horn Any progress on this?

**Comment by karl-horn** [comment]
> @karl-horn Any progress on this?

I have been a bit occupied by other stuff until now, so I haven't gotten started yet.
I will try to work on in the next few days.
