### ISSUE TITLE
Add state-to-state and square-modulus functionals

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#33]
For the sake of completeness, we need `F_sm`, `F_ss`, `J_T_sm`, `J_T_ss`, `chis_sm`, `chis_ss`.

@MatthiKrauss, thanks for adding these in b8dea5c7f7d7af5d314d15a9070b0c2db33de318

Could you also add basic tests for these functionals in `tests/test_functionals.py` (similar to the existing tests for the other functionals)? The added routines should have complete coverage, see `make coverage` locally, or https://coveralls.io/github/qucontrol/krotov?branch=master after pushing.

Lastly, can you add the names of the new functions to the `__all__` list in `src/krotov/functionals.py`? This is just the convention of declaring the "public" routines in a module.

**Comment by goerz** [comment]
@FernandoGago I noticed you're using the `J_T_ss` functional now in the STIRAP examples. While that makes sense in principle, it doesn't really go together with also transforming the target state in the rotating frame. Unless you want to reach a target state with a specific phase, as with the original `J_T_re` functional, it'll be really confusing the have the RWA transformation in the example notebook. I recommend that you switch back to `J_T_re`.

**Comment by FernandoGago** [comment]
Yes, that is true. But then again in that problem we are only trying to trasfer population from one state to another, and in that sense I thought it would be more appropriate to only use that functional. 

However, I am aware that when using that functional and only in our particular example, it makes the transformation to the rotating frame useless. It would be different if we used a different target state, such as |1> + |3>. The reason for leaving both of them was just trying to provide a more general example to the public. 

But I will switch to `J_T_re` then and maybe the `J_T_ss` can be used in another example .

**Comment by goerz** [comment]
Your intuition is 100% correct. Physically, for a population transfer, `J_T_ss` is better-motivated, unless we come up with a motivation for having a particular phase, like using STIRAP to implement an "effective π pulse", where the phase factor should be `-1j`, I believe (based on `b(1, 0, t=np.pi)` in https://nbviewer.jupyter.org/gist/goerz/85b6b3c1633378cee797).

But if we don't use this example for the RWA-correction to the targets, the only other place to do it is in the "3 states" example, but there it's a bit of a pain to calculate. I might still do it, after I fix the propagation.

In principle, I don't think we absolutely need an example that uses `J_T_ss` or `J_T_sm`. They should be in the library for completeness, and they're tested, so that should be enough.
