### ISSUE TITLE
Review section "Krotov's method"

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#37]
In 262aea39a9313083b26c8da1bb5c8bdc8dd9b757, I've rewritten the section "Krotov's Method" in the documentation according to our discussion from earlier this week.

* [ ] @FernandoGago @karl-horn @MatthiKrauss, please review the section to check if you find it easier to understand now, especially in regard to the use of the second order, and the time discretization

* [x] @danielreich Can you give this another quick review for mathematical correctness and consistent use of indices?

You may check off the above two boxes when you've finished the review, so that I can close this issue.

Please feel free to directly rewrite anything that you feel can be expressed more clearly, or any typos you see.

**Comment by danielreich** [comment]
Done

**Comment by FernandoGago** [comment]
In my opinion the new version is much more clear. 

Great job.

**Comment by goerz** [comment]
Great! I'll consider this closed then. If anybody else has further comments, please still feel free to add them.
