### ISSUE TITLE
Add Howto entry on spectral constraints

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#40]
This should mainly point out that you can do spectral constraints simply by applying a spectral filter after each iteration, but if @danielreich want's to add a sentence about the "proper" spectral constraints, that could go in there as well (with the the caveat that this is a fairly big change in Krotov's method, and not supported or planned by the implementation in the package)

**Comment by danielreich** [comment]
I think for now we should keep it as it is and avoid any potential confusion since implementing the spectral constraints with a Fredholm solver is quite the complex matter and goes very far beyond the current scope. I am happy to keep this entry in the current state.
