### ISSUE TITLE
Wrong definition of τ leads to wrong χsm and χss

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#46]
There is an incongruity between the current definition of τ = ⟨ϕ(T)|ϕtgt⟩ and the definition of e.g. χss = τ ϕtgt and χsm = (∑τ) ϕtgt. As a result, Example 1 (stage-to-state transition in a TLS) does not converge monotonically if `J_T_ss` is used instead of `J_T_re`. It would work with χss = τ⁺ ϕtgt, but the better solution is to redefine τ as ⟨ϕtgt | ϕ(T)⟩. This is in fact the original definition from `PalaoPRA2003`.

Incidentally, QDYN's documentation is also confused about this: the τ are correctly calculated as ⟨ϕtgt | ϕ(T)⟩, but the documentation claims that they are ⟨ϕ(T)|ϕtgt⟩, in `oct_funcs.F90`. @Basilewitsch, can you make sure this gets added to QDYN's TODO list?

**Comment by Basilewitsch** [comment]
No need to add it to QDYN's TODO list, should be fixed by the latest commit.
