### ISSUE TITLE
automatically build PDFs of example notebooks 

### ISSUE THREAD

**Issue by TejasAvinashShetty** [qucontrol/krotov#53]
Krotov version: stable
Python version: 3.7
Operating System: Ubuntu 18.04
### Description
I was trying to convert the example Jupyter notebooks   
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by TejasAvinashShetty** [comment]
[autoamtically build PDFs](https://github.com/qutip/qutip-notebooks/tree/master/examples/pdf)

**Comment by goerz** [comment]
We'll consider this as part of #52
