### ISSUE TITLE
modify simple state transfer notebook for Gate optimization 

### ISSUE THREAD

**Issue by TejasAvinashShetty** [qucontrol/krotov#55]
* Krotov version: 0.3.0
* Python version: 3.7.4
* Operating System: Ubuntu

### Description
I tried to modify the [simple_state_to_state](https://github.com/qucontrol/krotov/blob/master/docs/notebooks/01_example_simple_state_to_state.ipynb) notebook  to perform gate optimization with the goal of $sigma_y$ gate. But apparently, the optimization unable to effect any change in the cost function.
### What I Did
So inspired by this [code block](https://www.dropbox.com/s/abrco4tq3w5gdiq/screenshot-arxiv.org-2019.10.21-21_52_51.png) in the [arXiv paper associated with the package](https://arxiv.org/abs/1902.11284).

![Imgur](https://i.imgur.com/Oj7S6LE.png)
 I modified this [code cell](https://www.dropbox.com/s/l5p4c3611smf6sz/screenshot-localhost_8888-2019.10.21-21_53_37.png?dl=0) in [simple_state_to_state](https://github.com/qucontrol/krotov/blob/master/docs/notebooks/01_example_simple_state_to_state.ipynb) notebook
![Imgur](https://imgur.com/dkubRCJ.png) to [this](https://www.dropbox.com/s/l5p4c3611smf6sz/screenshot-localhost_8888-2019.10.21-21_53_37.png?dl=0).
![Imgur](https://i.imgur.com/9siu7bz.png)
Unfortunately, that completely stopped krotov optimization from [progressing](https://www.dropbox.com/s/5r25we9c0bxky2j/screenshot-localhost_8888-2019.10.21-22_04_32.png?dl=0) further. 
![mgur](https://imgur.com/tfhyGkI.png)

**Comment by goerz** [comment]
Can you upload your notebook as a [gist](https://gist.github.com) and link it here?

**Comment by TejasAvinashShetty** [comment]
Here is the [gist](https://gist.github.com/TejasAvinashShetty/bdeb362c0d30429a4b6cda2a0dad96ac).

**Comment by TejasAvinashShetty** [comment]
If there's a problem rendering the [gist](https://gist.github.com/TejasAvinashShetty/bdeb362c0d30429a4b6cda2a0dad96ac) as I have,  you can copy the URL into https://nbviewer.jupyter.org/.

**Comment by goerz** [comment]
I'm quite sure this is a controllability issue (the Y gate you are asking for cannot physically be realized). You can optimize for an X gate instead and use the square-modulus functional, see https://gist.github.com/goerz/d62fcabc2f2d3e97dd0cc32a115227d0.

In general, if in doubt, you should do a controllability analysis before running an optimization, see Chapter 3 of the book D'Allesandro - Introduction to Quantum Control and Dynamics, or section 2.3.3 of my PhD thesis for the one-page summary.

I'll close this since it doesn't look like a bug in `krotov`, but we can reopen if I'm wrong.

**Comment by TejasAvinashShetty** [comment]
Thank you, Dr @goerz. I will look into it.

**Comment by TejasAvinashShetty** [comment]
Dear Dr @goerz, I have thought further about this issue and these are my thoughts. Please let me know what are your comments.
![Screenshot from 2019-12-26 14-19-11](https://user-images.githubusercontent.com/27445854/71468070-ce962b80-27ea-11ea-8dc3-8928582da38f.png)

**Comment by TejasAvinashShetty** [comment]
I am sorry for wasting your time. But, even after thinking a lot, I am unable to resolve this vexing issue by myself.
