### ISSUE TITLE
How did you get this conclusion?

### ISSUE THREAD

**Issue by tesla-cat** [qucontrol/krotov#78]
- How did you get this conclusion?

![](https://qucontrol.github.io/krotov/v1.2.0/_images/oct_decision_tree.svg)

**Comment by goerz** [comment]
This is explained in detail in https://doi.org/10.21468/SciPostPhys.7.6.080

**Comment by tesla-cat** [comment]
> This is explained in detail in https://doi.org/10.21468/SciPostPhys.7.6.080
@goerz 
thanks!
do you have any code for **GOAT**?

**Comment by goerz** [comment]
I do not, sorry.

**Comment by tesla-cat** [comment]
> I do not, sorry.

if you don't have the code for `GOAT`, how do you know it is only suitable for $20<n<100$  ?

**Comment by goerz** [comment]
The numerical scaling is described in the GOAT paper, from which we can draw conclusions about feasibility based on our experience with gradient ascent, as well as some private discussion with the GOAT authors.

Anyway, we'd like to keep these Github issues centered on bug reports or questions about the implementation details of the Krotov package. General questions regarding the accompanying paper are best raised using the contact information given in the paper. For questions about GOAT, please contact the GOAT authors.
