### ISSUE TITLE
Add example notebook for optimization with a non-Hermitian Hamiltonian

### ISSUE THREAD

**Issue by goerz** [qucontrol/krotov#9]
Add an example notebook that optimizes the transfer from state 1 to state 3 in a Lambda-sytem, with a Pump and a Stokes laser, in the rotating wave approximation.

Dissipation from level 2 is modeled by a non-Hermitian Hamiltonian (decay term on level 2). ~Physically, this is the same as #4, but using a simpler numerical method.~ It should ~yield similar results as #4, and~ compare to the non-dissipative version #3.

At a technical level, this ensures that the backward propagation correctly uses the conjugate Hamiltonian.

**Comment by goerz** [comment]
Prerequisite for #13

**Comment by goerz** [comment]
Since #3 is closed, I think there shouldn't be anything blocking work on this example. @FernandoGago Will you have some time to work on this this week? You can start with a copy of #3, and just change the Hamiltonian.

**Comment by FernandoGago** [comment]
Yes, I hope to have this finished this by the end of this week.

**Comment by goerz** [comment]
Thanks, looks good! 👍

I'll do a few minor tweaks, and then close the issue.
