### ISSUE TITLE
using different form of cost function instead of fidelity 

### ISSUE THREAD

**Issue by Leeseok-628** [qucontrol/krotov#98]
Hi, 

I have been wondering if I can use krotov to optimize different forms of cost function, other than fidelity. 
For instance, would it be possible to optimize trace(rho_target - rho_ansatz) where rho_target is target density matrix and rho_ansatz is the time-evolved state under control parameters. If so, how?

Additionally, suppose we have some random operator A. Then is it possible to minimize the trace distance between the two density operators mutilplied by this operator A: i.e. trace(A(rho_target - rho_ansatz)). Does this also feasible via krotov?

**Comment by christianekoch** [comment]
Of course!
Your request corresponds to "Optimization of a Dissipative State-to-State Transfer in a Lambda System" listed as one of the examples in the package documentation. 
In case of a mixed target state, please see  https://doi.org/10.1002/qute.201800110 for potential pitfalls in defining your target functional.

**Comment by christianekoch** [comment]
The answer to your second question is also, yes. This would simply be the optimization of an expectation value difference which is one of the standard optimization tasks.

**Comment by Leeseok-628** [comment]
Thank you so much for your response! I read through the example, it helped me a lot. 

How can I customize (or build) my own cost function that goes into `krotov.optimize_pulses` function? Regarding my second question earlier, as you mentioned above, the cost function is tr(D(rho_tar - rho_trial)) = <psi_trial|D|psi_trial> - <psi_target|D|psi_target>, for given D and psi_target. But I don't see how to customize/code the cost function in this form of summation of two expectation values. The objectives that goes into `krotov.optimize_pulses` requires one to set initial and final states within some Hamiltonian, but I'm not quite sure how to build objectives when I need to calculate the expectation value of given operator D as my cost function. I'm confused on this because, I looked into the details of `krotov functional` (https://qucontrol.github.io/krotov/v1.0.0/API/krotov.functionals.html#module-krotov.functionals), and it seems like all functionals don't deal with expectation values! 

I'd really appreciate it if you can help me out with this :)
